name: Notify Slack on PR Open

on:
    pull_request:
        types: [opened]

jobs:
    notify-slack:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Restore Slack PR cache
              uses: actions/cache@v4
              with:
                  path: .slack-cache
                  key: slack-pr-tracker-${{ github.repository }}

            - name: Create cache folder if missing
              run: mkdir -p .slack-cache

            - name: Validate Slack configuration
              run: |
                  if [ -z "${{ secrets.SLACK_CHANNEL_ID }}" ]; then
                    echo "::error::SLACK_CHANNEL_ID secret is not set"
                    exit 1
                  fi
                  if [ -z "${{ secrets.SLACK_BOT_TOKEN }}" ]; then
                    echo "::error::SLACK_BOT_TOKEN secret is not set"
                    exit 1
                  fi
                  echo "Slack configuration is valid"

            - name: Send Slack message
              id: slack
              uses: slackapi/slack-github-action@v2.1.1
              with:
                  method: chat.postMessage
                  token: ${{ secrets.SLACK_BOT_TOKEN }}
                  payload: |
                      {
                        "channel": "${{ secrets.SLACK_CHANNEL_ID }}",
                        "text": "🔔 New PR needs review: <${{ github.event.pull_request.html_url }}|${{ github.event.pull_request.title }}>"
                      }
              env:
                  SLACK_BOT_TOKEN: ${{ secrets.SLACK_BOT_TOKEN }}

            - name: Save Slack timestamp
              run: |
                  echo "${{ github.event.pull_request.number }}=${{ steps.slack.outputs.ts }}" >> .slack-cache/tracker.txt
